FROM mysql:5.6

RUN { \
    echo '[mysqld]'; \
    echo 'character-set-server = utf8mb4'; \
    echo 'collation_server = utf8mb4_general_ci'; \
} > /etc/mysql/conf.d/charset.cnf

ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes
